### ISSUE TITLE
Subfolders?

### ISSUE THREAD

**Issue by donnekgit** [dmpop/mejiro#19]
This is a very nice little script.  I'm having one difficulty, though: in the docs it says: "Photos inside the default photo directory can be organized into subfolders."  However, when I put a folder "others" (containing some photos) inside the "photos" folder, it isn't listed?  Is there anything special I need to do to activate that feature?

**Comment by dmpop** [comment]
You just need to point the browser to the added subfolder. For example, if your Mejiro URL is *http://127.0.0.1/mejiro* and you have a subfolder named *monkey*, then the URL to this subfolder will be *http://127.0.0.1/mejiro/?d=monkey*.

**Comment by donnekgit** [comment]
I tried that earlier, but going to http://localhost/mejiro/?d=others gives an error message:
"photos/others/ or photos/others/tims directory doesn't exist. You must create it manually."  But I have ...

**Comment by dmpop** [comment]
You must make the *others* subdirectory and its contents writable by the server.

**Comment by donnekgit** [comment]
Yup, done that too, using the suggested `chown www-data -R mejiro`:
```
drwxrwxr-x  4 www-data kevin  4096 May 16 14:48 mejiro
drwxrwxr-x 4 www-data kevin   4096 May 16 14:24 photos
drwxrwxr-x 2 www-data kevin   4096 May 16 14:27 others
```

**Comment by dmpop** [comment]
Try `chown www-data:www-data -R mejiro/photos/others`.
