### ISSUE TITLE
PHP 7.x supported?

### ISSUE THREAD

**Issue by s-timm** [dmpop/mejiro#22]
Hi! 

Just a question: is PHP 7.x supported? 

I tried to install Mejiro on my Strato-hosted web space but I can't see any photos or thumbnails. Also, no thumbnails are being created in the "photos/tims" folder.
GD is installed, I changed folder/file permissions to 777... but maybe it's the PHP version: I have to use version 7.1, 7.2 or 7.3

Any help? 
thanx

**Comment by rpoulin** [comment]
I think u need image magic

**Comment by dmpop** [comment]
Should work with PHP7.x.x just fine. Have you changed permission for all subdirectories too?

**Comment by s-timm** [comment]
First, thanks for "Mejiro" :-)
I analysed your _index.php_-file and apparently the problem is the GLOB_BRACE flag - my hoster Strato seems to run Solaris servers and that flag is not supported on their hardware/software (see here: https://www.php.net/manual/en/function.glob.php).
As a workaround I replaced line 143 with 
`$files = array_merge(glob($photo_dir."*.[jJ][pP][gG]"),glob($photo_dir."*.[jJ][pP][eE][gG]"));`

That did the trick :-)

**Comment by dmpop** [comment]
Good to know. Thank you for following up on this!
