### ISSUE TITLE
Some photos don't show up in the gallery

### ISSUE THREAD

**Issue by irgendlink** [dmpop/mejiro#37]
Hello, I have a problem with showing up some photos. The photos are .jpg and they are in the photos directory and in the .tims directory. I can see the thumbnail in the grid. But when I click to enlarge it there is nothing to see. I tried Firefox and Chromium Browser. I also cleared the .tims directory  to process the photos again.
The gallery is at
https://irgendlink.de/umap/umsland-by1
The first photo in the gallery with the title 0001.jpg is an example for photos that do not show up. The other photos work fine. The attachment shows the exifdata of the photo that does not work and of another photo that works fine.
[exifdata-mejiro-issue-photo-does-not-appear.txt](https://github.com/dmpop/mejiro/files/13326047/exifdata-mejiro-issue-photo-does-not-appear.txt)
Thank you for your great work. I use it also to feed a umap with the csv.php file that I found in your Linux photo book. It works fine.
Juergen

**Comment by dmpop** [comment]
What happens if you rename the file from `0001.jpg`to, for example, `image.jpg`?

**Comment by irgendlink** [comment]
I also thought, it is a problem with the Exif. Meanwhile I processed the images again at my computer and uploaded them to a gallery and it works fine. File 0001.jpg is currently a rename of a file that was on the server for a long time. I copied it from an old mejiro-instance.
I append the file and it's tim, that I downloaded from the server.
Many thanks for your work.
![0001-tim](https://github.com/dmpop/mejiro/assets/62496641/da177b7f-8c99-4288-9c96-b366a7102c61)
![0001](https://github.com/dmpop/mejiro/assets/62496641/e63e7b37-81ae-46dd-951a-5cf8ab57cc88)

**Comment by dmpop** [comment]
The image works fine on my end. I do see PHP warnings about missing EXIF values, but they are not critical. Perhaps it is a problem with file permissions? But if you say it works now, I'm going to close the issue.

P.S. I think we're neighbors: I live in Fürth. Aber mein Deutsch ist eine Katastrophe. :smile:
